### PR TITLE
Create PurelyCosmeticCustomChat

### PR DESCRIPTION
**Pull request by RubberDuck55**

### CODE REVIEW

**Comment by PatheticMustan** [comment]
Good job! Since I figure somebody somewhere is going to find out anyways, I'm going to add back custom chat.

**Comment by Avn1114** [comment]
Ok, if you think it's really a good idea...

**Comment by GyarGG** [comment]
Well really, what’s the point anyway if no one else can see it

**Comment by PatheticMustan** [comment]
Eh, I guess it's purely cosmetic, the only point is to show off cool screenshots, I guess.

**Pull request merged**
