### PR TITLE
Please Update Battle_God.js

### PR DESCRIPTION
**Pull request by FelixN0324**
This has been tested and are working fine. I found the Barrier hack but they glitch the game.
temp2.player.modifiers.barrier=true;

Can Someone improve this hack?

### CODE REVIEW

**Comment by Robo-ren** [comment]
Hello felix

**Comment by Robo-ren** [comment]
I think we have to talk from here because the other web someone said we can't talk

**Comment by FelixN0324** [comment]
Do you have a Microsoft account, Robo-Ren?

**Comment by Robo-ren** [comment]
Yes

**Comment by Robo-ren** [comment]
I do

**Comment by Robo-ren** [comment]
Do I send u it?

**Comment by FelixN0324** [comment]
yes, message me at 3399441428@stu.gcsnc.com

**Comment by Robo-ren** [comment]
Ok

**Comment by Robo-ren** [comment]
but u think I could text u by school?

**Pull request merged**
