### PR TITLE
Update CheatMenuWIP.js

### PR DESCRIPTION
**Pull request by RubberDuck55**
Added Bookmarklet and Instakill

### CODE REVIEW

**Comment by PatheticMustan** [comment]
I invited you as collaborator, now you don't need to make PRs anymore! 🎉

**Comment by RubberDuck55** [comment]
I can't seem to find your request.

**Comment by PatheticMustan** [comment]
https://github.com/PatheticMustan/ProdigyMathGameHacking/invitations

Also it's "Pathetic" and "Mustan"

**Comment by GyarGG** [comment]
unrelated but...
BRuh i just checked my email an hour ago

>

**Comment by Avn1114** [comment]
Like 5000 emails, right?

**Pull request merged**
